/**
 * Typed accessor over the Nathal.IA 2D asset catalog.
 *
 * The data is generated by `scripts/nathalia/2d/catalog_assets.py` into
 * `./nathaliaSpriteCatalog.generated.ts` (and the canonical
 * `assets/2d/catalog.json`). This module adds the types and small, pure helpers
 * the layered avatar uses — it never touches `window` and is SSR-safe.
 *
 * The catalog is the single source of truth for *which* assets exist, so the
 * layered avatar can decide, at runtime, whether a layer (body, viseme, object)
 * is populated or whether it must fall back gracefully. See
 * `docs/nathalia/2D_ANIMATION_ARCHITECTURE.md`.
 */
import { NATHALIA_SPRITE_CATALOG } from "./nathaliaSpriteCatalog.generated";

export type NathaliaSpriteCategory =
  | "expression"
  | "viseme"
  | "object"
  | "body"
  | "face"
  | "face_base"
  | "eye"
  | "mouth"
  | "source";

/** A single catalogued image with its measured metadata. */
export interface NathaliaSprite {
  fileName: string;
  /** Repo-relative path (rastreabilidade). */
  path: string;
  /** Static URL when served (e.g. `/nathalia/expressions/x.webp`), else null. */
  webUrl: string | null;
  rootLabel: string;
  category: NathaliaSpriteCategory | string;
  subCategory: string;
  orientation: string | null;
  expression: string | null;
  suggestedUse: string;
  width: number;
  height: number;
  hasAlpha: boolean;
  bytes: number;
  notes: string;
}

/** Which conceptual layers currently have art (drives compositing vs fallback). */
export interface NathaliaLayerPresence {
  body: boolean;
  faceBase: boolean;
  face: boolean;
  eyes: boolean;
  mouths: boolean;
  visemes: boolean;
  objects: boolean;
  poses: boolean;
  accessories: boolean;
}

const DATA = NATHALIA_SPRITE_CATALOG as unknown as {
  schemaVersion: number;
  counts: { total: number; byCategory: Record<string, number> };
  layersPresent: NathaliaLayerPresence;
  assets: NathaliaSprite[];
};

/** All catalogued sprites (immutable). */
export const nathaliaSprites: readonly NathaliaSprite[] = DATA.assets;

/** Layer-presence summary from the catalog. */
export const nathaliaLayersPresent: NathaliaLayerPresence = DATA.layersPresent;

/** Count of assets per category. */
export const nathaliaSpriteCounts: Record<string, number> = DATA.counts.byCategory;

/** All sprites in a category, in catalog order. */
export function spritesByCategory(category: NathaliaSpriteCategory): NathaliaSprite[] {
  return nathaliaSprites.filter((s) => s.category === category);
}

/** Find a sprite by category + subCategory (e.g. expression "pensativa", viseme "a"). */
export function spriteFor(
  category: NathaliaSpriteCategory,
  subCategory: string,
): NathaliaSprite | null {
  return (
    nathaliaSprites.find(
      (s) => s.category === category && s.subCategory === subCategory,
    ) ?? null
  );
}

/** The served URL of a sprite (or null when it is source-only). */
export function spriteUrl(sprite: NathaliaSprite | null | undefined): string | null {
  return sprite?.webUrl ?? null;
}

/**
 * Whether a conceptual layer is populated with art today. The layered avatar
 * uses this to skip absent layers and fall back to the expression bust.
 */
export function hasLayer(layer: keyof NathaliaLayerPresence): boolean {
  return Boolean(nathaliaLayersPresent[layer]);
}
