import type { BillingTypeItem, ClientItem } from "./types";

export const demoBillingTypes: BillingTypeItem[] = [
  {
    id: "bt-hourly",
    name: "Hora trabalhada",
    chargeType: "HOURLY",
    roundingRule: "NEAREST_15_MINUTES",
    description: "Cobrança por horas aprovadas no fechamento mensal.",
    howItWorks: "Cobra pelas horas aprovadas",
    example: "160h × R$ 180/h",
    active: true,
  },
  {
    id: "bt-monthly",
    name: "Mensalidade fixa",
    chargeType: "MONTHLY",
    roundingRule: "NONE",
    description: "Valor mensal fixo com controle de limite de horas.",
    howItWorks: "Valor fixo independente das horas",
    example: "R$ 25.000/mês",
    active: true,
  },
];

export const demoClients: ClientItem[] = [
  {
    id: "cli-atlas",
    name: "Atlas Energia",
    document: "12.345.678/0001-90",
    contactEmail: "financeiro@atlasenergia.com.br",
    logoUrl: "",
    billingTypeId: "bt-hourly",
    billingTypeName: "Hora por projeto",
    defaultHourlyRate: 260,
    monthlyFee: undefined,
    hourLimit: 160,
    roundingRule: "NEAREST_15_MINUTES",
    billingDay: 25,
    dueDay: 10,
    invoiceKind: "SERVICE",
    municipality: "Sao Paulo",
    issRate: 2.9,
    taxRules: "Retencao conforme contrato vigente.",
    status: "ACTIVE",
    projectCount: 2,
  },
  {
    id: "cli-nova",
    name: "Nova Retail",
    document: "98.765.432/0001-10",
    contactEmail: "contas@novaretail.com",
    logoUrl: "",
    billingTypeId: "bt-monthly",
    billingTypeName: "Mensalidade",
    defaultHourlyRate: undefined,
    monthlyFee: 42000,
    hourLimit: 220,
    roundingRule: "NONE",
    billingDay: 20,
    dueDay: 5,
    invoiceKind: "SERVICE",
    municipality: "Campinas",
    issRate: 3,
    taxRules: "",
    status: "ACTIVE",
    projectCount: 1,
  },
];

