/**
 * Seed knowledge base for Nathal.IA (Fase 8).
 *
 * Content is curated from the JumpFlow product docs, FAQs and screen copy —
 * NOT generated by an LLM and NOT pulled from live user data. Each document is
 * concept-level help (pt-BR). Restricted topics carry `roles` so the search
 * layer keeps them away from profiles that should not see them.
 *
 * Catalogue + sourcing notes: `docs/nathalia/KNOWLEDGE_BASE.md`.
 */
import type { KnowledgeDocument } from "./types";

export const knowledgeDocuments: KnowledgeDocument[] = [
  // ---------------------------------------------------------------- general
  {
    id: "general-what-is-jumpflow",
    title: "O que é o JumpFlow",
    body:
      "O JumpFlow é a plataforma da Jump para consultores: horas, skills, certificados, alocação em projetos, aprovações, valores por hora e visão operacional e financeira.",
    tags: ["jumpflow", "plataforma", "sobre", "produto"],
    context: "general",
    source: "docs/plataforma-jump-horas.md",
  },
  {
    id: "general-who-is-nathalia",
    title: "Quem é a Nathal.IA",
    body:
      "Sou a assistente do JumpFlow. Ajudo você a navegar, entender cada tela e responder dúvidas sobre horas, projetos, aprovações e relatórios. Por enquanto respondo com conteúdo curado, sem inteligência generativa.",
    tags: ["nathalia", "assistente", "ajuda", "o que voce faz"],
    context: "general",
    source: "packages/character-nathalia",
  },

  // ------------------------------------------------------------------ hours
  {
    id: "hours-how-to-log",
    title: "Como lançar horas",
    body:
      "Escolha o período (semana), selecione o projeto e a atividade, informe as horas por dia e salve. O lançamento começa como Rascunho e fica editável até você enviar para aprovação.",
    tags: ["lancar", "registrar", "apontar", "horas", "timesheet", "periodo"],
    context: "hours",
    source: "docs/backlog-mvp.md",
  },
  {
    id: "hours-how-to-submit",
    title: "Como enviar horas para aprovação",
    body:
      "Com o período preenchido, use o botão de enviar para aprovação. Depois de enviado, o período fica bloqueado para edição até o aprovador analisar.",
    tags: ["enviar", "submeter", "aprovacao", "horas", "bloqueio"],
    context: "hours",
    source: "docs/backlog-mvp.md",
  },
  {
    id: "hours-status-meaning",
    title: "O que significa cada status das horas",
    body:
      "Rascunho = ainda editável; Enviado = aguardando aprovação; Aprovado = validado pelo aprovador; Reprovado = precisa de ajuste e reenvio.",
    tags: ["status", "rascunho", "enviado", "aprovado", "reprovado", "horas"],
    context: "hours",
    source: "docs/modelo-dados.md",
  },
  {
    id: "hours-edit-rejected",
    title: "Como corrigir horas reprovadas",
    body:
      "Quando um período é reprovado, ele volta a ficar editável. Ajuste os lançamentos conforme o comentário do aprovador e envie novamente para aprovação.",
    tags: ["reprovado", "corrigir", "ajustar", "reenviar", "horas"],
    context: "hours",
    source: "docs/backlog-mvp.md",
  },

  // --------------------------------------------------------------- projects
  {
    id: "projects-overview",
    title: "O que vejo na tela de Projetos",
    body:
      "A lista de projetos com cliente, responsável e situação. Abra um projeto para ver detalhes, alocações e vínculos. Campos sensíveis podem ficar ocultos conforme o seu perfil.",
    tags: ["projetos", "lista", "cliente", "responsavel", "detalhes"],
    context: "projects",
    source: "apps/web/src/app/app/projetos",
  },
  {
    id: "projects-allocation",
    title: "O que é alocação em projeto",
    body:
      "Alocação é o vínculo de um consultor a um projeto. Ela é a base para lançar horas e para os valores por hora. Mudanças sensíveis de alocação exigem perfil adequado.",
    tags: ["alocacao", "vinculo", "consultor", "projeto", "valor hora"],
    context: "projects",
    source: "docs/modelo-dados.md",
  },
  {
    id: "projects-my-projects",
    title: "Quais projetos estão vinculados a mim",
    body:
      "Seus projetos são aqueles em que você tem uma alocação ativa. É a partir desse vínculo que você consegue lançar horas para o projeto.",
    tags: ["meus projetos", "vinculados", "alocado", "consultor"],
    context: "projects",
    source: "apps/web/src/app/app/projetos",
  },

  // -------------------------------------------------------------- approvals
  {
    id: "approvals-how-queue-works",
    title: "Como funciona a fila de aprovação",
    body:
      "Os itens enviados (horas e despesas) aparecem na fila para análise. O aprovador revisa e aprova ou reprova com um comentário. Reprovar devolve o item para ajuste.",
    tags: ["fila", "aprovar", "reprovar", "analise", "aprovacao", "horas", "despesas"],
    context: "approvals",
    roles: ["ADMIN", "AREA_MANAGER", "PROJECT_MANAGER", "FINANCE"],
    source: "docs/backlog-mvp.md",
  },
  {
    id: "approvals-auto",
    title: "O que é aprovação automática",
    body:
      "São regras que aprovam itens dentro de critérios definidos, reduzindo trabalho manual. A configuração das regras é restrita à gestão e fica registrada em auditoria.",
    tags: ["aprovacao automatica", "regras", "automacao", "criterios"],
    context: "approvals",
    roles: ["ADMIN", "AREA_MANAGER", "PROJECT_MANAGER", "FINANCE"],
    source: "apps/web/src/app/app/automacoes/aprovacao-automatica",
  },

  // --------------------------------------------------------------- reports
  {
    id: "reports-which-exist",
    title: "Quais relatórios existem",
    body:
      "Há relatórios de horas, de despesas e um consolidado. Você pode filtrar por período e exportar. O alcance dos dados segue o seu perfil.",
    tags: ["relatorios", "horas", "despesas", "consolidado", "exportar", "filtro"],
    context: "reports",
    source: "apps/web/src/app/app/relatorios",
  },
  {
    id: "reports-scope",
    title: "Por que vejo só alguns dados nos relatórios",
    body:
      "O alcance segue o seu perfil: consultores veem os próprios dados; gestores veem os projetos sob sua responsabilidade. Isso protege dados de outras pessoas.",
    tags: ["escopo", "alcance", "perfil", "rbac", "relatorios", "dados"],
    context: "reports",
    source: "docs/arquitetura.md",
  },

  // ---------------------------------------------------------------- finance
  {
    id: "finance-closing",
    title: "O que é o fechamento financeiro",
    body:
      "O fechamento consolida as horas aprovadas e os valores do período. Eu explico o conceito, mas não mostro valores: eles seguem as regras de acesso financeiro.",
    tags: ["fechamento", "financeiro", "consolidacao", "periodo", "margem"],
    context: "finance",
    roles: ["ADMIN", "AREA_MANAGER", "FINANCE"],
    source: "docs/backlog-mvp.md",
  },

  // --------------------------------------------------------------- settings
  {
    id: "settings-access",
    title: "O que dá para fazer em Acessos",
    body:
      "Convidar pessoas, definir grupos de acesso (perfis) e bloquear usuários. Esta área é restrita a administradores e mudanças ficam registradas em auditoria.",
    tags: ["acessos", "convite", "perfis", "permissoes", "admin", "rbac"],
    context: "settings",
    roles: ["ADMIN"],
    source: "apps/web/src/app/app/admin/acessos",
  },
];
